# Generated by Django 3.1.5 on 2021-01-29 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ingredients', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('preparation', models.CharField(max_length=256, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(default=datetime.datetime.now)),
                ('preparation_time', models.IntegerField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
